# Generated by Django 5.2.7 on 2025-10-26 16:01

import django.db.models.deletion
import quejas_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('reporter_name', models.CharField(blank=True, max_length=120, verbose_name='Nombre del reportante')),
                ('reporter_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del reportante')),
                ('reporter_phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('status', models.CharField(choices=[('new', 'Nueva'), ('in_progress', 'En progreso'), ('resolved', 'Resuelta'), ('rejected', 'Rechazada')], default='new', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('assigned_to', models.CharField(blank=True, max_length=150, verbose_name='Asignado a')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='quejas_app.category')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por Usuario')),
            ],
            options={
                'verbose_name': 'Queja',
                'verbose_name_plural': 'Quejas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=120, verbose_name='Autor (Opcional)')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('public', models.BooleanField(default=False, help_text='Si está marcado, el comentario será visible públicamente', verbose_name='Público')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Comentador')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='quejas_app.complaint')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=quejas_app.models.attachment_upload_path, verbose_name='Archivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Subido')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='quejas_app.complaint')),
            ],
            options={
                'verbose_name': 'Adjunto',
                'verbose_name_plural': 'Adjuntos',
            },
        ),
    ]
